#---Config---
Config.Version: 1

#---verification---
Verification.ComputationalVerification.Enabled: true
Verification.ComputationalVerification.Timeout: 15

#---Chat---
Chat.Enabled: true
Chat.SpeakingInterval: 3
Chat.MaxMessageLength: 100
Chat.CanStoreTheNumberOfSpeeches: 20
Chat.BannedString:
  - '\n'

Chat.DuplicateMessageDetection.Enabled: true
#I don't know if this is the correct way to write it, but I didn't find a better word. :(
Chat.DuplicateMessageDetection.TextPrint.Enabled: true
Chat.DuplicateMessageDetection.TextPrint.Similarity: 0.9

#---Network---
Network.Host: '127.0.0.1'
Network.MaximumConnectionsPerIp: 5
Network.PlayerCapPerIp: 10
Network.MaximumPingsPerSecond: 3


#---Player---
Player.WhileList.Enabled: true
Player.Whitelist.ActivityThreshold: 1000
Player.Name.Regex: '^[a-zA-Z0-9_]{1,16}$'


#---Message---
Message.Prefix: '&f[FAS]'
Message.KickedForTooManyConnections: '{prefix}&4Your IP has reached the maximum number of connections.'
Message.KickedForCheck: '{prefix}&a\n------------\nAnalyzing your connection\nPlease login again\n------------'
Message.KickedForUnderAttack: '{underAttack} please wait'
Message.UnderAttack: '{prefix}&4Server is attacked.'
Message.ValueValidationChallengeText: '{prefix}&l&aPlease answer the following questions:\n{question}\nto remove the restriction.'
Message.TalkingTooMuchReminder: '{prefix}&4Excessive speech.'
Message.UnauthenticatedActionWarning: '{prefix}&l&aCannot operate without verification!'
Message.VerificationSuccessPrompt: '{prefix}&l&aYou are now verified.'
Message.ChatDisabledWarning: '{prefix}&4Chat is not enabled.'
Message.MessageTooLongWarning: '{prefix}&4Message is too long.'
Message.BannedStringWarning: '{prefix}&4You are not allowed to use this string.'
Message.ComputeVerificationFailed: '{prefix}&4Failed to verify.'
Message.ComputeVerificationTimeout: '{prefix}&4Verification timeout.'
