#---Config---
Config:
  Version: 1
  # (kick/ban)
  Mode: 'kick'

#---verification---
Verification:
  ComputationalVerification:
    Enabled: true
    Timeout: 15
  BanMCStormFreePlanBot:
    Enabled: true

#---Chat---
Chat:
  Enabled: true
  SpeakingInterval: 3
  MaxMessageLength: 100
  CanStoreTheNumberOfSpeeches: 20
  BannedString:
    - '\n'

  DuplicateMessageDetection:
    Enabled: true
    #I don't know if this is the correct way to write it, but I didn't find a better word. :(
    TextPrint:
      Enabled: true
      Similarity: 0.9
  AntiCommand:
    Enabled: true
    CommandWhiteList:
      - '/l'
      - '/login'
      - '/reg'
      - '/register'

#---Network---
Network:
  Host: '127.0.0.1'
  MaximumConnectionsPerIp: 5
  PlayerCapPerIp: 10
  MaximumPingsPerSecond: 3


#---Player---
Player:
  WhileList:
    Enabled: true
    ActivityThreshold: 1000
  Name:
    Regex: '^[a-zA-Z0-9_]{1,16}$'


#---Message---
Message:
  Prefix: '&f[FAS]'
  KickedForTooManyConnections: '{prefix}&4Your IP has reached the maximum number of connections.'
  KickedForCheck: '{prefix}&a\n------------\nAnalyzing your connection\nPlease login again\n------------'
  KickedForUnderAttack: '{underAttack} please wait'
  KickedForIllegalName: '&cYour name does not match \"^[a-zA-Z0-9_]{3,16}\$\", please change your name'
  UnderAttack: '{prefix}&4Server is attacked.'
  ValueValidationChallengeText: '{prefix}&l&aPlease answer the following questions:\n{question}\nto remove the restriction.'
  TalkingTooMuchReminder: '{prefix}&4Excessive speech.'
  UnauthenticatedActionWarning: '{prefix}&l&aCannot operate without verification!'
  VerificationSuccessPrompt: '{prefix}&l&aYou are now verified.'
  ChatDisabledWarning: '{prefix}&4Chat is not enabled.'
  MessageTooLongWarning: '{prefix}&4Message is too long.'
  BannedStringWarning: '{prefix}&4You are not allowed to use this string.'
  ComputeVerificationFailed: '{prefix}&4Failed to verify.'
  ComputeVerificationTimeout: '{prefix}&4Verification timeout.'
